# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Install TypeScript globally since tsc is needed for build
RUN npm install -g typescript

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Start the MCP server
CMD [ "node", "build/index.js" ]
